title: Bee Appreciation
description: A website detailing the flowering lives of bees and the recipes to
  use honey in.
footer_text: Copyright 2020 Macy Holden
header_feature_image: ../uploads/pages.jpg
header_text: Bee, Bees and more Bees
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
