title: The Official Website of Holden Honey Hives
description: What more could a bee want?
footer_text: Copyright 2020
header_feature_image: ../uploads/bianca-ackermann-mtnvvqvmoks-unsplash.jpg
header_text: ""
header_text_color: "#e0982b"
bannerheight: 50vmax
logo: ../uploads/hhh-logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: false
