title: The Official Website of Holden Honey Hives
description: A website dedicated to the enlightenment of bees, delicious honey
  recipes and providing helpful advice on a variety of subjects using our own
  personal experiences.
footer_text: Copyright 2020
header_feature_image: ../uploads/bianca-ackermann-mtnvvqvmoks-unsplash.jpg
header_text: What more could a bee want?
header_text_color: "#e0982b"
bannerheight: 50vmax
logo: ../uploads/hhh-logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items: []
